### ISSUE TITLE
Error when running on Windows Anaconda

### ISSUE THREAD

**Issue by tlbauer2** [sandialabs/galen-view#1]
Created a new anaconda environment in windows 10 and installed _as per_ the directions.  I got the following error: 

```
 Uncaught exception POST /api/sessions (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/api/sessions', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "c:\users\travis\anaconda3\envs\galen\lib\site-packages\tornado\web.py", line 1703, in _execute
        result = await result
      File "c:\users\travis\anaconda3\envs\galen\lib\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "c:\users\travis\anaconda3\envs\galen\lib\site-packages\notebook\services\sessions\handlers.py", line 69, in post
        model = yield maybe_future(
      File "c:\users\travis\anaconda3\envs\galen\lib\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "c:\users\travis\anaconda3\envs\galen\lib\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "c:\users\travis\anaconda3\envs\galen\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
        kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
      File "c:\users\travis\anaconda3\envs\galen\lib\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "c:\users\travis\anaconda3\envs\galen\lib\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "c:\users\travis\anaconda3\envs\galen\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 100, in start_kernel_for_session
        kernel_id = yield maybe_future(
      File "c:\users\travis\anaconda3\envs\galen\lib\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "c:\users\travis\anaconda3\envs\galen\lib\site-packages\tornado\gen.py", line 209, in wrapper
        yielded = next(result)
      File "c:\users\travis\anaconda3\envs\galen\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "c:\users\travis\anaconda3\envs\galen\lib\site-packages\jupyter_client\multikernelmanager.py", line 158, in start_kernel
        km.start_kernel(**kwargs)
      File "c:\users\travis\anaconda3\envs\galen\lib\site-packages\jupyter_client\manager.py", line 301, in start_kernel
        kernel_cmd, kw = self.pre_start_kernel(**kw)
      File "c:\users\travis\anaconda3\envs\galen\lib\site-packages\jupyter_client\manager.py", line 248, in pre_start_kernel
        self.write_connection_file()
      File "c:\users\travis\anaconda3\envs\galen\lib\site-packages\jupyter_client\connect.py", line 468, in write_connection_file
        self.connection_file, cfg = write_connection_file(self.connection_file,
      File "c:\users\travis\anaconda3\envs\galen\lib\site-packages\jupyter_client\connect.py", line 138, in write_connection_file
        with secure_write(fname) as f:
      File "c:\users\travis\anaconda3\envs\galen\lib\contextlib.py", line 113, in __enter__
        return next(self.gen)
      File "c:\users\travis\anaconda3\envs\galen\lib\site-packages\jupyter_core\paths.py", line 435, in secure_write
        win32_restrict_file_to_user(fname)
      File "c:\users\travis\anaconda3\envs\galen\lib\site-packages\jupyter_core\paths.py", line 361, in win32_restrict_file_to_user
        import win32api
    ImportError: DLL load failed while importing win32api: The specified module could not be found.
```

**Comment by tlbauer2** [comment]
This appears to the be same error as reported here:  https://youtrack.jetbrains.com/issue/PY-39047

**Comment by tlbauer2** [comment]
A workaround for the moment is to use the Ubuntu windows subsystem and install the Linux version of anaconda.  That's how the software was originally tested in Windows.

**Comment by tlbauer2** [comment]
It also works to use conda to install holoviews rather than relying on pip.  I updated the directions so the user will use "conda install holoviews" before pip installing galen-view so that holoviews is already installed.
